name: piece_fruits
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  url_launcher: ^6.1.4
  intl: ^0.17.0
  path: ^1.8.1
  yaml: ^3.1.1
  percent_indicator: ^4.2.2
  package_info_plus: ^1.4.3
  
  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/layout/
    - assets/images/icons/
    - assets/images/avatars/portrait/1/
    - assets/images/avatars/thumbnail/1/
    - assets/images/avatars/portrait/2/
    - assets/images/avatars/thumbnail/2/
    - assets/images/avatars/portrait/3/
    - assets/images/avatars/thumbnail/3/
    - assets/images/avatars/portrait/4/
    - assets/images/avatars/thumbnail/4/
    - assets/images/avatars/portrait/5/
    - assets/images/avatars/thumbnail/5/
    - assets/images/avatars/portrait/6/
    - assets/images/avatars/thumbnail/6/
    - assets/images/avatars/portrait/7/
    - assets/images/avatars/thumbnail/7/
    - assets/images/avatars/portrait/8/
    - assets/images/avatars/thumbnail/8/   
    - assets/images/avatars/portrait/9/
    - assets/images/avatars/thumbnail/9/
    - assets/images/avatars/portrait/10/
    - assets/images/avatars/thumbnail/10/             

  fonts:
    - family: Dosis
      fonts:    
        - asset: assets/fonts/dosis/Dosis-ExtraLight.ttf
          weight: 200      
        - asset: assets/fonts/dosis/Dosis-Light.ttf
          weight: 300      
        - asset: assets/fonts/dosis/Dosis-Regular.ttf
          weight: 400
        - asset: assets/fonts/dosis/Dosis-Medium.ttf
          weight: 500
        - asset: assets/fonts/dosis/Dosis-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/dosis/Dosis-Bold.ttf
          weight: 700        
        - asset: assets/fonts/dosis/Dosis-ExtraBold.ttf
          weight: 800
    - family: Lato
      fonts:    
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100      
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300      
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700        
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900          

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/icons/icon.png